# Programming Assignment 2
#### Raymundo, Lorenz Nelson L. | 2ECE-A

### Normalization

In [1]:
import numpy as np

In [43]:
# Create a 5x5 array with random values
x = np.random.random([5,5])

# Get the mean and standard deviation
mean = x.mean()
sd = x.std()

# normalize x using the formula z = ( x - mean ) / sd
norm_x = (x-mean)/sd

print(norm_x)

np.save('X_normalized.npy', norm_x)
print("\n\nNormalized ndarray saved to 'X_normalized.npy'")

[[ 0.46719563 -0.27482734  1.52859282 -0.76116417 -0.98951996]
 [-0.94789948  1.46934552 -0.25690212 -1.73325249  0.61876956]
 [-0.15460963  0.93505331 -1.24129754  1.06614896  0.35275793]
 [-0.80453372 -1.08095152 -0.79304773  0.23959149  0.3154695 ]
 [ 0.78992004  1.55979733 -1.63856771 -0.15985977  1.49379111]]


Normalized ndarray saved to 'X_normalized.npy'


### Divisible by 3

In [45]:
# Create a 10x10 array of the squares of the first 100 positive integers
x = np.arange(1,101)
x_1 = x.reshape(10,10) #
x_2 = x_1**2

orig_by_3 = x[x % 3 == 0]
x_3 = orig_by_3.reshape(3,11)

squared_by_3 = x_2[x_2 % 3 == 0]
x_4 = squared_by_3.reshape(3,11)

print("Original Array:\n", x_1)
print("\n Array with squared values:\n", x_2)
print("\n Original elements divisible by 3:\n", x_3)
print("\n Squared elements divisible by 3:\n", x_4)

np.save('div_by_3.npy', x_3, x_4)
print("\n\n Elements divisible by 3 saved to 'div_by_3.npy'")

Original Array:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

 Array with squared values:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  688